# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
      #before_script:
      #- julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/PieterjanRobbe/SimpleMultigrid.jl", rev="master")); using SimpleMultigrid'
      #- julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/PieterjanRobbe/NotSoSimpleMultigrid.jl", rev="master")); using NotSoSimpleMultigrid'
      #- julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/PieterjanRobbe/MultilevelEstimators.jl", rev="master")); using MultilevelEstimators'
env:
  - PYTHON=""
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("LognormalDiffusionProblems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("LognormalDiffusionProblems")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
